compile process cannot fail anymore. because it always fails otherwise.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,2 +1,21 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
+
+set -e
+set -o pipefail
+
+BUILD_DIR=$1
+
+cd $BUILD_DIR
+
+LD_LIBRARY_PATH=$BUILD_DIR/lib:$BUILD_DIR/bin ldd "$1"/bin/server | grep "not found"
+if [ $? -eq 0 ] ; then
+  echo "-----> Some dependencies cannot be found..."
+# exit -1
+else
+  echo "-----> Successfully found all the dependencies."
+fi
+
+#echo "-----> Running tests"
+#bin/tests
+
